### ISSUE TITLE
log4shell documention for building from source is incorrect

### ISSUE THREAD

**Issue by aregier** [lunasec-io/lunasec#1162]
https://github.com/lunasec-io/lunasec/tree/master/lunatrace/cli/cmd/log4shell

This page states that the following build steps should work:
```
docker build . -t log4shell
docker run --network=host log4shell
```

However, there isn't even a Dockerfile in this project folder, so the steps don't work.

Short of that, would it be possible for lunasec to sign their executables in the download page with Apple so they are trusted binaries?

**Comment by breadchris** [comment]
hey @aregier thanks for raising this issue. Unfortunately we are not capable of maintaining this project anymore. The dockerfile you are looking for is located here https://github.com/lunasec-io/lunasec/blob/master/lunatrace/cli/docker/log4shell.dockerfile
