### ISSUE TITLE
False positive Log4J Checks - JndiLookup.class

### ISSUE THREAD

**Issue by pathetiq** [lunasec-io/lunasec#327]
Hi,

The constants for Log4J vulnerability are looking at the hash of the _JndiLookup.class_ which was actually not modified between versions 2.15 and 2.16. This results in a false positive saying that the version 2.16 (up to date) of the class is still at 2.15 and stating that this is a vulnerability which is wrong.

**Files**
- [constant fill to remove JndiLookup.class verification](https://github.com/lunasec-io/lunasec/blob/8eb17dbaa529f3d4a0d3f0a9acb9dc62b0dca21b/tools/log4shell/constants/vulnerablehashes.go)

When checking the hash on both 2.15 and 2.16 you can see the JndiLookup.class files are identical:

```
md5 JndiLookup16.class 
MD5 (JndiLookup16.class) = 737b430fac6caef7c485c9c47f0f9104

bash-3.2$ md5 JndiLookup15.class 
MD5 (JndiLookup15.class) = 737b430fac6caef7c485c9c47f0f9104
```

**Files for checks:**
- [2.15](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.15.0/log4j-core-2.15.0.jar)
- [2.16](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar)

Let me know if you have any question!

**Comment by johnatannvmd** [comment]
Can confirm this

**Comment by freeqaz** [comment]
Thank you for opening this issue -- we're sorting this out now (we've gotten pinged about this a bunch). Good fun!

**Comment by breadchris** [comment]
#342 these changes resolves this issue.

**Comment by breadchris** [comment]
Latest release https://github.com/lunasec-io/lunasec/releases/tag/v1.4.0-log4shell
