### ISSUE TITLE
WRN unable to open archive

### ISSUE THREAD

**Issue by RinaldoC** [lunasec-io/lunasec#328]
Many jar make this error
WRN unable to open archive error="zip: not a valid zip file" 
It's possible to know why ? Manual unzip it and launch the tool on unzipped dir can be a workaround ?

**Comment by breadchris** [comment]
Similar to #299

I think adding more code around why a certain file is not a valid zip file might be out of scope for the scanner. Having the warning is there to let you know that further investigation on those specific files is needed.

We could update the logging statement to reflect this with something such as "Unable to scan zip file _. Manual analysis might be required."

**Comment by andybirenzi** [comment]
Is there a known workaround for " not a valid zip file" error while trying to scan a .jar file?

**Comment by breadchris** [comment]
Could you clarify what you mean by "workaround"?

Are you trying to see if there is a way to fix an invalid zip file?

**Comment by andybirenzi** [comment]
It's possible I misunderstood how this tool works, but I compiled my springboot application , got a .jar file, deployed it to a dev server through CI/CD to make sure it works fine and it worked, I then used the same .jar file to scan using this tool (I'm on Windows), but I'm still getting " not a valid zip file", It's not clear why this tool sees this .jar as invalid zip while it works fine when deployed on a server

**Comment by l-lang** [comment]
> Many jar make this error WRN unable to open archive error="zip: not a valid zip file" It's possible to know why ? Manual unzip it and launch the tool on unzipped dir can be a workaround ?

On my scans this warning occurs when scanning a .jar-symlink that points to a .jar file. The original .jar file is properly scanned without warning. I guess the tool does not follow symlinks.

**Comment by RinaldoC** [comment]
> On my scans this warning occurs when scanning a .jar-symlink that points to a .jar file. The original .jar file is properly scanned without warning. I guess the tool does not follow symlinks.

The problem isn't (only) on symlink: i tried on a directory with only one problematic jar and same problem

> Similar to #299
> 
> I think adding more code around why a certain file is not a valid zip file might be out of scope for the scanner. Having the warning is there to let you know that further investigation on those specific files is needed.
> 
> We could update the logging statement to reflect this with something such as "Unable to scan zip file _. Manual analysis might be required."

I wouldn't like to ignore the jar file...i would like to scan it ;-)
Problematic Jar file are  spring boot generated jar (with embedded tomcat) that work perfectly in production environment and that i can manual unzip (with common unzip command from shell) without error, so i don't understend why the tool recognize this file as "not valid zip file"

**Comment by cukal** [comment]
I also planned on scanning a load of Springboot applications but got the same error, springboot files are (high-level) basically script files that start with an executable #! shebang while the actual binary jar/zip file is appended after the scripting portion, hence making them executable. Too bad, I guess I will continue with ```unzip -l <springboot.jar>``` which does show the contents but does not expand into possible included jar files.

**Comment by bolshoytoster** [comment]
"zip: not a valid zip file" is thrown by `zip.NewReader `:
https://github.com/lunasec-io/lunasec/blob/cf60212495ef3d708a85ba9ab6d9a8e708b2de59/tools/log4shell/scan/scan.go#L129-L131
It is thrown when a zip header is incorrectly formatted, other methods of unzipping (i.e. the `unzip` command) probably have error handling for this.

**Comment by breadchris** [comment]
@cukal can you share me one of those generated files so I can throw it into my tests? I feel there will be a number of people running into this issue.

**Comment by RinaldoC** [comment]
@breadchris I found the "combinantion" that give problems: projects with Spring Boot < 2.0 when  crate an executable jar

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <executable>true</executable>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by breadchris** [comment]
im having a hard time trying to replicate the creation of this type of jar file. @RinaldoC or @cukal can you provide me a `pom.xml` or an executable jar for spring boot < 2.0 which has the weird header?

**Comment by RinaldoC** [comment]
@breadchris 
[log4jtest-0.0.1-SNAPSHOT.jar.gz](https://github.com/lunasec-io/lunasec/files/7743153/log4jtest-0.0.1-SNAPSHOT.jar.gz)
[pom.xml.zip](https://github.com/lunasec-io/lunasec/files/7743159/pom.xml.zip)

**Comment by breadchris** [comment]
awesome @RinaldoC thank you

**Comment by fschollmeyer** [comment]
Another jar file that can reproduce this is the official openzipkin release downloaded from https://github.com/openzipkin/zipkin: https://search.maven.org/remote_content?g=io.zipkin&a=zipkin-server&v=LATEST&c=exec

**Comment by breadchris** [comment]
Fixed in 1.5.1
