### ISSUE TITLE
.ear package files

### ISSUE THREAD

**Issue by luis-alves** [lunasec-io/lunasec#340]
I see a reference to the scanning of war, jar and zip files. Does the scan also reads the contents of Ear files?

**Comment by acollign** [comment]
Hi @luis-alves , i've made PR for the EAR extension https://github.com/lunasec-io/lunasec/pull/334. At the moment, the EAR extension is not considered as an archive and therefore is not analysed.

**Comment by freeqaz** [comment]
I just landed that PR, and we'll package up a release with that change today. For now, just grab the source and build it yourself if you need this feature until then.

I'll throw another comment here when we finish up packaging this change + the other PRs from the last day. Cheers!

**Comment by acollign** [comment]
Thanks @freeqaz. Good luck with the release!

**Comment by luis-alves** [comment]
Thanks @acollign for the PR, I'm sure many people will benefit from it! Great work!
I built and tested it, and it works, as it should.

**Comment by factoidforrest** [comment]
added in #334
