### ISSUE TITLE
False positive between 2.14.1 and 2.15.0/2.16.0

### ISSUE THREAD

**Issue by freeqaz** [lunasec-io/lunasec#349]
It looks like we're hashing a file that's the same between these versions, and that's creating a false positive for people.

This was introduced when we started generating the hashes ourselves from files off of Maven vs using hashes from [this](https://github.com/hillu/local-log4j-vuln-scanner/blob/master/log4j-vuln-finder.go#L16) repo.

Fix is to find files that hash to different values for each of these versions, which I'm going to do manually now and then cut a release. Opening this issue to track it in case somebody runs into this.

**Comment by breadchris** [comment]
#342 addresses this false positive

**Comment by breadchris** [comment]
Latest release https://github.com/lunasec-io/lunasec/releases/tag/v1.4.0-log4shell
