### ISSUE TITLE
POM project 12:00PM | warn | Unable to parse semver version 

### ISSUE THREAD

**Issue by flyasky** [lunasec-io/lunasec#379]
**Describe the bug**
Lot's of lines like
```
12:00PM | warn | Unable to parse semver version
        fileName: spring-web-5.2.14.RELEASE
        semverVersion:
```
when analyzing spring-boot project root with pom.xml

**Expected behavior**
Clean log.

**Desktop (please complete the following information):**
 - Win 10 + WSL Ubuntu 20.04
 - N/A
 - 1.4.2

**Comment by breadchris** [comment]
@flyasky if you are trying to look for vulnerable libraries which are vulnerable to log4shell, you must use the `scan` command and not `analyze`. analyze is used when creating library signatures to look for when scanning.
