### ISSUE TITLE
How to run log4shell_1.4.2-log4shell_Linux_x86_64

### ISSUE THREAD

**Issue by s31t0n** [lunasec-io/lunasec#385]
Hi,
can you please advice on how to run this file?
It has non extention, i should be .tar.gz.
Thank you.

**Comment by breadchris** [comment]
Hey @s31t0n! You can download and run the cli with this:
```
curl -O https://github.com/lunasec-io/lunasec/releases/download/v1.4.1-log4shell/log4shell_1.4.1-log4shell_Linux_x86_64
chmod +x log4shell_1.4.1-log4shell_Linux_x86_64
./log4shell_1.4.1-log4shell_Linux_x86_64
```

I am realizing that our blog post is saying to extract the file, but it is actually an executable file that you can just run. Hopefully  you can get it running with the above command!

I will keep this issue open until I land those changes.

**Comment by breadchris** [comment]
See #386
