### ISSUE TITLE
VirusTotal shows 4 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by bscardina** [lunasec-io/lunasec#396]
4/67 scanners report a Trojan.
Cylance
Unsafe
MaxSecure
Trojan.Malware.300983.susgen
Rising
Trojan.Generic@ML.87 (RDML:fGe6bRIqDvA/1X3XGGuFkg)
SecureAge APEX
Malicious

Please review.

**Comment by breadchris** [comment]
hey @bscardina, we appreciate you bringing this to our attention and we have made a note about this. Thank you!
