### ISSUE TITLE
Add Topics to LunaTrace

### ISSUE THREAD

**Issue by freeqaz** [lunasec-io/lunasec#540]
Tasks:
- [ ] Agree on spec for Topics
  - [ ] Attach CVEs to Topics
  - [ ] (Question) Do we use Docusaurus and ingest that into the Production DB?
- [ ] Add a hardlink to a topic that can be linked to externally (like from a blog post)
- [ ] View a list of projects and builds affected by a specific Topic (all vulnerabilities)

**Comment by factoidforrest** [comment]
Sounds like we probably want topic bodies to come from some git repo, to use all of the editing and collaboration features already present in github.  

Discussion remains around how the metadata will work, particularly anything relational.  I argue we could build those controls into the app behind an "admin" boolean.  The other option is we could copy paste them into a yaml file and write a parser to pull them back out and put them in the database.
