### ISSUE TITLE
Refactor docs to reflect LunaTrace and LunaDefend separation

### ISSUE THREAD

**Issue by breadchris** [lunasec-io/lunasec#559]
The current docs all reference "LunaDefend" as "LunaSec" and this needs to be updated.

The structure of the docs also needs to change so that they are organized into folders `LunaDefend` and `LunaTrace`

Old url links must be updated as to not have dead links.

**Comment by g00b** [comment]
Adding a page for explaining legacy info, specifically to reference the name change from LunaSec to LunaDefend in sections of code that may reference LunaSec
