### ISSUE TITLE
Add support for GitHub "Checks" API to make PR bot quieter

### ISSUE THREAD

**Issue by freeqaz** [lunasec-io/lunasec#632]
Right now we're dropping a comment on PRs. @factoidforrest added support to disable this comment, since it's a bit noisy, but we should probably just default to using a "check" by default.

In GitHub this would be a green checkmark in the "Checks" box on the bottom of every PR. Our CLA agreement does basically exactly this.

**Comment by ajvpot** [comment]
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning

https://docs.github.com/en/rest/checks/runs#create-a-check-run
